# Generated by Django 5.0.7 on 2024-10-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CONNECT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bword',
            old_name='word',
            new_name='name',
        ),
    ]
