# Generated by Django 5.0.7 on 2024-10-09 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONNECT', '0003_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='userxx', max_length=100000),
        ),
    ]
